### ISSUE TITLE
Missing array parser.

### ISSUE THREAD

**Issue by SimonArdrey** [propelorm/Propel#33]
When calling toArray, toXML, toCSV ... on an Object derived from BaseObject also on a PropelCollection an exception is generated.

```
Fatal error: Uncaught exception 'PropelException' with message 'Unknown parser class "PropelArrayParser"' in /home/neoguard/public_html/_data1/core/thirdparty/propel/runtime/lib/parser/PropelParser.php:95
Stack trace:
#0 /home/neoguard/public_html/_data1/core/thirdparty/propel/runtime/lib/om/BaseObject.php(354): PropelParser::getParser('Array')
#1 /home/neoguard/public_html/_data1/core/thirdparty/propel/runtime/lib/om/BaseObject.php(380): BaseObject->exportTo('Array')
#2 /home/neoguard/public_html/_data1/models/build/classes/neoguardian/om/BaseDevice.php(2057): BaseObject->__call('toArray', Array)
#3 /home/neoguard/public_html/_data1/core/thirdparty/propel/runtime/lib/collection/PropelObjectCollection.php(134): BaseDevice->__call('toArray', Array)
#4 /home/neoguard/public_html/_data1/core/thirdparty/propel/runtime/lib/collection/PropelObjectCollection.php(134): Device->toArray('phpName', true, Array, true)
#5 /home/neoguard/public_html/_data1/core/thirdparty/propel/runtime/lib/collection/PropelCollection.php(466): PropelO in /home/neoguard/public_html/_data1/core/thirdparty/propel/runtime/lib/parser/PropelParser.php on line 95
```

From what I understand the exportTo function of the BaseObject tries to call toArray but no such function exists, so the __call function redirects it to exportTo('Array') which tried to load PropelArrayParser.php which does not exist.

Is this a bug or am I doing something wrong?

Thanks

**Comment by muhammad-yasin** [comment]
I have this error 
Unknown parser class "Propel\Runtime\Parser\KeyvalueParser" 
any Idea on this
